/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Persona API
 * ### Introduction  Use the Numeno Persona API to create and manage **Personas**.  Evolving a Persona over time is dead-simple: [create a Persona](create-persona), then send natural-language descriptions of your users’ in-app activities to the Persona API. Under the hood, we create a rich set of models of the system that evolve over time.  Then, ask Numeno to personalize some part of your experience using the Persona.  Numeno will use our models to tailor your software to each user’s unique preferences and habits, allowing you to dynamically adjust your offerings.  For example, connect a Persona to the **[Numeno Article Recommender API](https://numeno.ai/wp-content/uploads/docs/artrec/numeno-article-recommender-api)** to generate **Article Feeds** that evolve over time as your Persona evloves with user interaction.  Personas are not limited to modelling users. Posts in a social environment, articles or topics on a content platform, a screen or widget in your UI, a product in your inventory - groups of any of these things – Personas can evolve models of anything in your system!  Get creative!
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ErrorDetail
 */
export interface ErrorDetail {
  /**
   * Field where the error occurred (if applicable).
   * @type {string}
   * @memberof ErrorDetail
   */
  field?: string
  /**
   * Description of the error.
   * @type {string}
   * @memberof ErrorDetail
   */
  message?: string
}

/**
 * Check if a given object implements the ErrorDetail interface.
 */
export function instanceOfErrorDetail(value: object): value is ErrorDetail {
  return true
}

export function ErrorDetailFromJSON(json: any): ErrorDetail {
  return ErrorDetailFromJSONTyped(json, false)
}

export function ErrorDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorDetail {
  if (json == null) {
    return json
  }
  return {
    field: json['field'] == null ? undefined : json['field'],
    message: json['message'] == null ? undefined : json['message'],
  }
}

export function ErrorDetailToJSON(json: any): ErrorDetail {
  return ErrorDetailToJSONTyped(json, false)
}

export function ErrorDetailToJSONTyped(
  value?: ErrorDetail | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    field: value['field'],
    message: value['message'],
  }
}
