/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Persona API
 * ### Introduction  Use the Numeno Persona API to create and manage **Personas**.  Evolving a Persona over time is dead-simple: [create a Persona](create-persona), then send natural-language descriptions of your users’ in-app activities to the Persona API. Under the hood, we create a rich set of models of the system that evolve over time.  Then, ask Numeno to personalize some part of your experience using the Persona.  Numeno will use our models to tailor your software to each user’s unique preferences and habits, allowing you to dynamically adjust your offerings.  For example, connect a Persona to the **[Numeno Article Recommender API](https://numeno.ai/wp-content/uploads/docs/artrec/numeno-article-recommender-api)** to generate **Article Feeds** that evolve over time as your Persona evloves with user interaction.  Personas are not limited to modelling users. Posts in a social environment, articles or topics on a content platform, a screen or widget in your UI, a product in your inventory - groups of any of these things – Personas can evolve models of anything in your system!  Get creative!
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Information needed to create a persona.
 * @export
 * @interface PersonaNew
 */
export interface PersonaNew {
  /**
   * The name of the Persona for easy reference.
   * @type {string}
   * @memberof PersonaNew
   */
  name: string
  /**
   * The natural-language body of the Persona.
   * @type {string}
   * @memberof PersonaNew
   */
  body: string
}

/**
 * Check if a given object implements the PersonaNew interface.
 */
export function instanceOfPersonaNew(value: object): value is PersonaNew {
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('body' in value) || value['body'] === undefined) return false
  return true
}

export function PersonaNewFromJSON(json: any): PersonaNew {
  return PersonaNewFromJSONTyped(json, false)
}

export function PersonaNewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PersonaNew {
  if (json == null) {
    return json
  }
  return {
    name: json['name'],
    body: json['body'],
  }
}

export function PersonaNewToJSON(json: any): PersonaNew {
  return PersonaNewToJSONTyped(json, false)
}

export function PersonaNewToJSONTyped(
  value?: PersonaNew | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    name: value['name'],
    body: value['body'],
  }
}
