/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Persona API
 * ### Introduction  Use the Numeno Persona API to create and manage **Personas**.  Evolving a Persona over time is dead-simple: [create a Persona](create-persona), then send natural-language descriptions of your users’ in-app activities to the Persona API. Under the hood, we create a rich set of models of the system that evolve over time.  Then, ask Numeno to personalize some part of your experience using the Persona.  Numeno will use our models to tailor your software to each user’s unique preferences and habits, allowing you to dynamically adjust your offerings.  For example, connect a Persona to the **[Numeno Article Recommender API](https://numeno.ai/wp-content/uploads/docs/artrec/numeno-article-recommender-api)** to generate **Article Feeds** that evolve over time as your Persona evloves with user interaction.  Personas are not limited to modelling users. Posts in a social environment, articles or topics on a content platform, a screen or widget in your UI, a product in your inventory - groups of any of these things – Personas can evolve models of anything in your system!  Get creative!
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Information needed to update a persona.
 * @export
 * @interface PersonaUpdate
 */
export interface PersonaUpdate {
  /**
   * The name of the Persona for easy reference.
   * @type {string}
   * @memberof PersonaUpdate
   */
  name?: string
  /**
   * The natural-language body of the Persona.
   * @type {string}
   * @memberof PersonaUpdate
   */
  body?: string
}

/**
 * Check if a given object implements the PersonaUpdate interface.
 */
export function instanceOfPersonaUpdate(value: object): value is PersonaUpdate {
  return true
}

export function PersonaUpdateFromJSON(json: any): PersonaUpdate {
  return PersonaUpdateFromJSONTyped(json, false)
}

export function PersonaUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PersonaUpdate {
  if (json == null) {
    return json
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    body: json['body'] == null ? undefined : json['body'],
  }
}

export function PersonaUpdateToJSON(json: any): PersonaUpdate {
  return PersonaUpdateToJSONTyped(json, false)
}

export function PersonaUpdateToJSONTyped(
  value?: PersonaUpdate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    name: value['name'],
    body: value['body'],
  }
}
