/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Persona API
 * ### Introduction  Use the Numeno Persona API to create new personas.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Persona } from './Persona'
import {
  PersonaFromJSON,
  PersonaFromJSONTyped,
  PersonaToJSON,
  PersonaToJSONTyped,
} from './Persona'

/**
 *
 * @export
 * @interface Personas
 */
export interface Personas {
  /**
   *
   * @type {Array<Persona>}
   * @memberof Personas
   */
  personas: Array<Persona>
  /**
   *
   * @type {string}
   * @memberof Personas
   */
  cursor?: string
}

/**
 * Check if a given object implements the Personas interface.
 */
export function instanceOfPersonas(value: object): value is Personas {
  if (!('personas' in value) || value['personas'] === undefined) return false
  return true
}

export function PersonasFromJSON(json: any): Personas {
  return PersonasFromJSONTyped(json, false)
}

export function PersonasFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Personas {
  if (json == null) {
    return json
  }
  return {
    personas: (json['personas'] as Array<any>).map(PersonaFromJSON),
    cursor: json['cursor'] == null ? undefined : json['cursor'],
  }
}

export function PersonasToJSON(json: any): Personas {
  return PersonasToJSONTyped(json, false)
}

export function PersonasToJSONTyped(
  value?: Personas | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    personas: (value['personas'] as Array<any>).map(PersonaToJSON),
    cursor: value['cursor'],
  }
}
