/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Admin API
 * ## Introduction  Use the Numeno Administration API to create API Keys and set their permissions (which we call Scopes). This API is meant to be used by administrators of your organization.  ## Scopes  Scopes are used to let API Keys access only certain parts of the API.  Scopes are expressed as a string of the form `api:resource:action`.  For example, from the Numeno Article Recommender API (`art-rec`):   - `art-rec:feeds:read` - can read any Feed (eg. `GET` `/feeds`, `/feeds/:id`, `/feeds/:id/streams`, etc.)   - `art-rec:feeds:write` - can write (and read) any Feed   - `art-rec:feeds:*` - can perform any action on Feeds   - `art-rec:*:read` - can read any resource on `art-rec`   - `*:*:*` - can do everything
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { ErrorDetail } from './ErrorDetail'
import {
  ErrorDetailFromJSON,
  ErrorDetailFromJSONTyped,
  ErrorDetailToJSON,
  ErrorDetailToJSONTyped,
} from './ErrorDetail'

/**
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
  /**
   * HTTP status code of the error.
   * @type {number}
   * @memberof ErrorResponse
   */
  status: number
  /**
   * A message describing the error.
   * @type {string}
   * @memberof ErrorResponse
   */
  message: string
  /**
   * Details about specific errors (if any).
   * @type {Array<ErrorDetail>}
   * @memberof ErrorResponse
   */
  errors?: Array<ErrorDetail>
}

/**
 * Check if a given object implements the ErrorResponse interface.
 */
export function instanceOfErrorResponse(value: object): value is ErrorResponse {
  if (!('status' in value) || value['status'] === undefined) return false
  if (!('message' in value) || value['message'] === undefined) return false
  return true
}

export function ErrorResponseFromJSON(json: any): ErrorResponse {
  return ErrorResponseFromJSONTyped(json, false)
}

export function ErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorResponse {
  if (json == null) {
    return json
  }
  return {
    status: json['status'],
    message: json['message'],
    errors:
      json['errors'] == null
        ? undefined
        : (json['errors'] as Array<any>).map(ErrorDetailFromJSON),
  }
}

export function ErrorResponseToJSON(json: any): ErrorResponse {
  return ErrorResponseToJSONTyped(json, false)
}

export function ErrorResponseToJSONTyped(
  value?: ErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    status: value['status'],
    message: value['message'],
    errors:
      value['errors'] == null
        ? undefined
        : (value['errors'] as Array<any>).map(ErrorDetailToJSON),
  }
}
