/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { KeyInfo } from './KeyInfo'
import {
  KeyInfoFromJSON,
  KeyInfoFromJSONTyped,
  KeyInfoToJSON,
  KeyInfoToJSONTyped,
} from './KeyInfo'

/**
 *
 * @export
 * @interface GetKeys200Response
 */
export interface GetKeys200Response {
  /**
   *
   * @type {Array<KeyInfo>}
   * @memberof GetKeys200Response
   */
  keys: Array<KeyInfo>
  /**
   *
   * @type {string}
   * @memberof GetKeys200Response
   */
  cursor?: string
}

/**
 * Check if a given object implements the GetKeys200Response interface.
 */
export function instanceOfGetKeys200Response(
  value: object,
): value is GetKeys200Response {
  if (!('keys' in value) || value['keys'] === undefined) return false
  return true
}

export function GetKeys200ResponseFromJSON(json: any): GetKeys200Response {
  return GetKeys200ResponseFromJSONTyped(json, false)
}

export function GetKeys200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetKeys200Response {
  if (json == null) {
    return json
  }
  return {
    keys: (json['keys'] as Array<any>).map(KeyInfoFromJSON),
    cursor: json['cursor'] == null ? undefined : json['cursor'],
  }
}

export function GetKeys200ResponseToJSON(json: any): GetKeys200Response {
  return GetKeys200ResponseToJSONTyped(json, false)
}

export function GetKeys200ResponseToJSONTyped(
  value?: GetKeys200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    keys: (value['keys'] as Array<any>).map(KeyInfoToJSON),
    cursor: value['cursor'],
  }
}
