/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { UserInfo } from './UserInfo'
import {
  UserInfoFromJSON,
  UserInfoFromJSONTyped,
  UserInfoToJSON,
  UserInfoToJSONTyped,
} from './UserInfo'

/**
 *
 * @export
 * @interface GetUsers200Response
 */
export interface GetUsers200Response {
  /**
   *
   * @type {Array<UserInfo>}
   * @memberof GetUsers200Response
   */
  users: Array<UserInfo>
  /**
   *
   * @type {string}
   * @memberof GetUsers200Response
   */
  cursor?: string
}

/**
 * Check if a given object implements the GetUsers200Response interface.
 */
export function instanceOfGetUsers200Response(
  value: object,
): value is GetUsers200Response {
  if (!('users' in value) || value['users'] === undefined) return false
  return true
}

export function GetUsers200ResponseFromJSON(json: any): GetUsers200Response {
  return GetUsers200ResponseFromJSONTyped(json, false)
}

export function GetUsers200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUsers200Response {
  if (json == null) {
    return json
  }
  return {
    users: (json['users'] as Array<any>).map(UserInfoFromJSON),
    cursor: json['cursor'] == null ? undefined : json['cursor'],
  }
}

export function GetUsers200ResponseToJSON(json: any): GetUsers200Response {
  return GetUsers200ResponseToJSONTyped(json, false)
}

export function GetUsers200ResponseToJSONTyped(
  value?: GetUsers200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    users: (value['users'] as Array<any>).map(UserInfoToJSON),
    cursor: value['cursor'],
  }
}
