/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Information about an API key, including the scopes it has access to
 * @export
 * @interface KeyInfoFull
 */
export interface KeyInfoFull {
  /**
   * The key that can be used to authenticate a request
   * @type {string}
   * @memberof KeyInfoFull
   */
  key: string
  /**
   * The user id that the key belongs to
   * @type {string}
   * @memberof KeyInfoFull
   */
  userId: string
  /**
   * The date the key was created in ISO 8601 datetime
   * @type {Date}
   * @memberof KeyInfoFull
   */
  createdAt?: Date
  /**
   * The date the key was last modified in ISO 8601 datetime
   * @type {Date}
   * @memberof KeyInfoFull
   */
  modifiedAt?: Date
  /**
   * The scopes that the key has access to
   * @type {Array<string>}
   * @memberof KeyInfoFull
   */
  scopes?: Array<string>
}

/**
 * Check if a given object implements the KeyInfoFull interface.
 */
export function instanceOfKeyInfoFull(value: object): value is KeyInfoFull {
  if (!('key' in value) || value['key'] === undefined) return false
  if (!('userId' in value) || value['userId'] === undefined) return false
  return true
}

export function KeyInfoFullFromJSON(json: any): KeyInfoFull {
  return KeyInfoFullFromJSONTyped(json, false)
}

export function KeyInfoFullFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): KeyInfoFull {
  if (json == null) {
    return json
  }
  return {
    key: json['key'],
    userId: json['userId'],
    createdAt:
      json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    modifiedAt:
      json['modifiedAt'] == null ? undefined : new Date(json['modifiedAt']),
    scopes: json['scopes'] == null ? undefined : json['scopes'],
  }
}

export function KeyInfoFullToJSON(json: any): KeyInfoFull {
  return KeyInfoFullToJSONTyped(json, false)
}

export function KeyInfoFullToJSONTyped(
  value?: KeyInfoFull | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    key: value['key'],
    userId: value['userId'],
    createdAt:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    modifiedAt:
      value['modifiedAt'] == null
        ? undefined
        : value['modifiedAt'].toISOString(),
    scopes: value['scopes'],
  }
}
