/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface KeyNew
 */
export interface KeyNew {
  /**
   * The scopes of the new key
   * @type {Array<string>}
   * @memberof KeyNew
   */
  scopes?: Array<string>
}

/**
 * Check if a given object implements the KeyNew interface.
 */
export function instanceOfKeyNew(value: object): value is KeyNew {
  return true
}

export function KeyNewFromJSON(json: any): KeyNew {
  return KeyNewFromJSONTyped(json, false)
}

export function KeyNewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): KeyNew {
  if (json == null) {
    return json
  }
  return {
    scopes: json['scopes'] == null ? undefined : json['scopes'],
  }
}

export function KeyNewToJSON(json: any): KeyNew {
  return KeyNewToJSONTyped(json, false)
}

export function KeyNewToJSONTyped(
  value?: KeyNew | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    scopes: value['scopes'],
  }
}
