/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { KeyInfo } from './KeyInfo'
import {
  KeyInfoFromJSON,
  KeyInfoFromJSONTyped,
  KeyInfoToJSON,
  KeyInfoToJSONTyped,
} from './KeyInfo'

/**
 *
 * @export
 * @interface Keys
 */
export interface Keys {
  /**
   *
   * @type {Array<KeyInfo>}
   * @memberof Keys
   */
  keys: Array<KeyInfo>
  /**
   *
   * @type {string}
   * @memberof Keys
   */
  cursor?: string
}

/**
 * Check if a given object implements the Keys interface.
 */
export function instanceOfKeys(value: object): value is Keys {
  if (!('keys' in value) || value['keys'] === undefined) return false
  return true
}

export function KeysFromJSON(json: any): Keys {
  return KeysFromJSONTyped(json, false)
}

export function KeysFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Keys {
  if (json == null) {
    return json
  }
  return {
    keys: (json['keys'] as Array<any>).map(KeyInfoFromJSON),
    cursor: json['cursor'] == null ? undefined : json['cursor'],
  }
}

export function KeysToJSON(json: any): Keys {
  return KeysToJSONTyped(json, false)
}

export function KeysToJSONTyped(
  value?: Keys | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    keys: (value['keys'] as Array<any>).map(KeyInfoToJSON),
    cursor: value['cursor'],
  }
}
