/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface NewKey
 */
export interface NewKey {
  /**
   * The scopes of the new key
   * @type {Array<string>}
   * @memberof NewKey
   */
  scopes?: Array<string>
}

/**
 * Check if a given object implements the NewKey interface.
 */
export function instanceOfNewKey(value: object): value is NewKey {
  return true
}

export function NewKeyFromJSON(json: any): NewKey {
  return NewKeyFromJSONTyped(json, false)
}

export function NewKeyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NewKey {
  if (json == null) {
    return json
  }
  return {
    scopes: json['scopes'] == null ? undefined : json['scopes'],
  }
}

export function NewKeyToJSON(json: any): NewKey {
  return NewKeyToJSONTyped(json, false)
}

export function NewKeyToJSONTyped(
  value?: NewKey | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    scopes: value['scopes'],
  }
}
