/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Information about a user
 * @export
 * @interface NewUser
 */
export interface NewUser {
  /**
   * The user id on our website
   * @type {string}
   * @memberof NewUser
   */
  webId: string
  /**
   * The tier of the user
   * @type {string}
   * @memberof NewUser
   */
  tier?: string
}

/**
 * Check if a given object implements the NewUser interface.
 */
export function instanceOfNewUser(value: object): value is NewUser {
  if (!('webId' in value) || value['webId'] === undefined) return false
  return true
}

export function NewUserFromJSON(json: any): NewUser {
  return NewUserFromJSONTyped(json, false)
}

export function NewUserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NewUser {
  if (json == null) {
    return json
  }
  return {
    webId: json['webId'],
    tier: json['tier'] == null ? undefined : json['tier'],
  }
}

export function NewUserToJSON(json: any): NewUser {
  return NewUserToJSONTyped(json, false)
}

export function NewUserToJSONTyped(
  value?: NewUser | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    webId: value['webId'],
    tier: value['tier'],
  }
}
