/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Information about a user
 * @export
 * @interface UpdateUser
 */
export interface UpdateUser {
  /**
   * The user id on our website
   * @type {string}
   * @memberof UpdateUser
   */
  webId?: string
  /**
   * The tier of the user
   * @type {string}
   * @memberof UpdateUser
   */
  tier?: string
}

/**
 * Check if a given object implements the UpdateUser interface.
 */
export function instanceOfUpdateUser(value: object): value is UpdateUser {
  return true
}

export function UpdateUserFromJSON(json: any): UpdateUser {
  return UpdateUserFromJSONTyped(json, false)
}

export function UpdateUserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUser {
  if (json == null) {
    return json
  }
  return {
    webId: json['webId'] == null ? undefined : json['webId'],
    tier: json['tier'] == null ? undefined : json['tier'],
  }
}

export function UpdateUserToJSON(json: any): UpdateUser {
  return UpdateUserToJSONTyped(json, false)
}

export function UpdateUserToJSONTyped(
  value?: UpdateUser | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    webId: value['webId'],
    tier: value['tier'],
  }
}
