/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UpdateKey
 */
export interface UpdateKey {
  /**
   * The scopes to add to the key, if any. Cannot overlap with removeScopes.
   * @type {Array<string>}
   * @memberof UpdateKey
   */
  addScopes?: Array<string>
  /**
   * The scopes to remove from the key, if any. Cannot overlap with addScopes.
   * @type {Array<string>}
   * @memberof UpdateKey
   */
  removeScopes?: Array<string>
}

/**
 * Check if a given object implements the UpdateKey interface.
 */
export function instanceOfUpdateKey(value: object): value is UpdateKey {
  return true
}

export function UpdateKeyFromJSON(json: any): UpdateKey {
  return UpdateKeyFromJSONTyped(json, false)
}

export function UpdateKeyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateKey {
  if (json == null) {
    return json
  }
  return {
    addScopes: json['addScopes'] == null ? undefined : json['addScopes'],
    removeScopes:
      json['removeScopes'] == null ? undefined : json['removeScopes'],
  }
}

export function UpdateKeyToJSON(json: any): UpdateKey {
  return UpdateKeyToJSONTyped(json, false)
}

export function UpdateKeyToJSONTyped(
  value?: UpdateKey | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    addScopes: value['addScopes'],
    removeScopes: value['removeScopes'],
  }
}
