/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { UserInfo } from './UserInfo'
import {
  UserInfoFromJSON,
  UserInfoFromJSONTyped,
  UserInfoToJSON,
  UserInfoToJSONTyped,
} from './UserInfo'

/**
 *
 * @export
 * @interface Users
 */
export interface Users {
  /**
   *
   * @type {Array<UserInfo>}
   * @memberof Users
   */
  users: Array<UserInfo>
  /**
   *
   * @type {string}
   * @memberof Users
   */
  cursor?: string
}

/**
 * Check if a given object implements the Users interface.
 */
export function instanceOfUsers(value: object): value is Users {
  if (!('users' in value) || value['users'] === undefined) return false
  return true
}

export function UsersFromJSON(json: any): Users {
  return UsersFromJSONTyped(json, false)
}

export function UsersFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Users {
  if (json == null) {
    return json
  }
  return {
    users: (json['users'] as Array<any>).map(UserInfoFromJSON),
    cursor: json['cursor'] == null ? undefined : json['cursor'],
  }
}

export function UsersToJSON(json: any): Users {
  return UsersToJSONTyped(json, false)
}

export function UsersToJSONTyped(
  value?: Users | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    users: (value['users'] as Array<any>).map(UserInfoToJSON),
    cursor: value['cursor'],
  }
}
