/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Information needed to create a new user
 * @export
 * @interface UserNew
 */
export interface UserNew {
  /**
   * The user id on our website
   * @type {string}
   * @memberof UserNew
   */
  webId: string
  /**
   * The tier of the user
   * @type {string}
   * @memberof UserNew
   */
  tier?: string
}

/**
 * Check if a given object implements the UserNew interface.
 */
export function instanceOfUserNew(value: object): value is UserNew {
  if (!('webId' in value) || value['webId'] === undefined) return false
  return true
}

export function UserNewFromJSON(json: any): UserNew {
  return UserNewFromJSONTyped(json, false)
}

export function UserNewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserNew {
  if (json == null) {
    return json
  }
  return {
    webId: json['webId'],
    tier: json['tier'] == null ? undefined : json['tier'],
  }
}

export function UserNewToJSON(json: any): UserNew {
  return UserNewToJSONTyped(json, false)
}

export function UserNewToJSONTyped(
  value?: UserNew | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    webId: value['webId'],
    tier: value['tier'],
  }
}
