/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Admin API  These are the admin APIs, not meant to be used by anyone but Numeno administration tools or the backend of the Numeno dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Information about a user
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
  /**
   * The user id
   * @type {string}
   * @memberof UserInfo
   */
  id: string
  /**
   * The user id on our website
   * @type {string}
   * @memberof UserInfo
   */
  webId?: string
  /**
   * The tier of the user
   * @type {string}
   * @memberof UserInfo
   */
  tier?: string
  /**
   * The date the user was created in ISO 8601 datetime
   * @type {Date}
   * @memberof UserInfo
   */
  createdAt?: Date
  /**
   * The date the user was last modified in ISO 8601 datetime
   * @type {Date}
   * @memberof UserInfo
   */
  modifiedAt?: Date
}

/**
 * Check if a given object implements the UserInfo interface.
 */
export function instanceOfUserInfo(value: object): value is UserInfo {
  if (!('id' in value) || value['id'] === undefined) return false
  return true
}

export function UserInfoFromJSON(json: any): UserInfo {
  return UserInfoFromJSONTyped(json, false)
}

export function UserInfoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserInfo {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    webId: json['webId'] == null ? undefined : json['webId'],
    tier: json['tier'] == null ? undefined : json['tier'],
    createdAt:
      json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    modifiedAt:
      json['modifiedAt'] == null ? undefined : new Date(json['modifiedAt']),
  }
}

export function UserInfoToJSON(json: any): UserInfo {
  return UserInfoToJSONTyped(json, false)
}

export function UserInfoToJSONTyped(
  value?: UserInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    webId: value['webId'],
    tier: value['tier'],
    createdAt:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    modifiedAt:
      value['modifiedAt'] == null
        ? undefined
        : value['modifiedAt'].toISOString(),
  }
}
