/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Introduction  Use the Numeno Article Recommender API to get personalized article recommendations in three easy steps:  1. Define a Persona: Simply provide a description of your interests, vibe, and target audience.  2. Associate the Persona with a Feed.  3. Pull from the Feed to receive a curated selection of articles from across the web.  ### Cross-Origin Resource Sharing This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/), allowing cross-domain communication from the browser. All responses have a wildcard same-origin policy which makes them accessible from any code on any site.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ErrorResponseErrorsInner
 */
export interface ErrorResponseErrorsInner {
  /**
   * Field where the error occurred (if applicable)
   * @type {string}
   * @memberof ErrorResponseErrorsInner
   */
  field?: string
  /**
   * Description of the error
   * @type {string}
   * @memberof ErrorResponseErrorsInner
   */
  message?: string
}

/**
 * Check if a given object implements the ErrorResponseErrorsInner interface.
 */
export function instanceOfErrorResponseErrorsInner(
  value: object,
): value is ErrorResponseErrorsInner {
  return true
}

export function ErrorResponseErrorsInnerFromJSON(
  json: any,
): ErrorResponseErrorsInner {
  return ErrorResponseErrorsInnerFromJSONTyped(json, false)
}

export function ErrorResponseErrorsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorResponseErrorsInner {
  if (json == null) {
    return json
  }
  return {
    field: json['field'] == null ? undefined : json['field'],
    message: json['message'] == null ? undefined : json['message'],
  }
}

export function ErrorResponseErrorsInnerToJSON(
  json: any,
): ErrorResponseErrorsInner {
  return ErrorResponseErrorsInnerToJSONTyped(json, false)
}

export function ErrorResponseErrorsInnerToJSONTyped(
  value?: ErrorResponseErrorsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    field: value['field'],
    message: value['message'],
  }
}
