/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Introduction  Use the Numeno Article Recommender API to get personalized article recommendations in three easy steps:  1. Define a Persona: Simply provide a description of your interests, vibe, and target audience.  2. Associate the Persona with a Feed.  3. Pull from the Feed to receive a curated selection of articles from across the web.  ### Cross-Origin Resource Sharing This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/), allowing cross-domain communication from the browser. All responses have a wildcard same-origin policy which makes them accessible from any code on any site.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Information needed to create a feed.
 * @export
 * @interface FeedNew
 */
export interface FeedNew {
  /**
   * The name of the feed for easy reference
   * @type {string}
   * @memberof FeedNew
   */
  name: string
}

/**
 * Check if a given object implements the FeedNew interface.
 */
export function instanceOfFeedNew(value: object): value is FeedNew {
  if (!('name' in value) || value['name'] === undefined) return false
  return true
}

export function FeedNewFromJSON(json: any): FeedNew {
  return FeedNewFromJSONTyped(json, false)
}

export function FeedNewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FeedNew {
  if (json == null) {
    return json
  }
  return {
    name: json['name'],
  }
}

export function FeedNewToJSON(json: any): FeedNew {
  return FeedNewToJSONTyped(json, false)
}

export function FeedNewToJSONTyped(
  value?: FeedNew | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    name: value['name'],
  }
}
