/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Introduction  Use the Numeno Article Recommender API to get personalized article recommendations in three easy steps:  1. Define a Persona: Simply provide a description of your interests, vibe, and target audience.  2. Associate the Persona with a Feed.  3. Pull from the Feed to receive a curated selection of articles from across the web.  ### Cross-Origin Resource Sharing This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/), allowing cross-domain communication from the browser. All responses have a wildcard same-origin policy which makes them accessible from any code on any site.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Persona } from './Persona'
import {
  PersonaFromJSON,
  PersonaFromJSONTyped,
  PersonaToJSON,
  PersonaToJSONTyped,
} from './Persona'

/**
 *
 * @export
 * @interface GetPersonas200Response
 */
export interface GetPersonas200Response {
  /**
   *
   * @type {Array<Persona>}
   * @memberof GetPersonas200Response
   */
  personas: Array<Persona>
  /**
   *
   * @type {string}
   * @memberof GetPersonas200Response
   */
  cursor?: string
}

/**
 * Check if a given object implements the GetPersonas200Response interface.
 */
export function instanceOfGetPersonas200Response(
  value: object,
): value is GetPersonas200Response {
  if (!('personas' in value) || value['personas'] === undefined) return false
  return true
}

export function GetPersonas200ResponseFromJSON(
  json: any,
): GetPersonas200Response {
  return GetPersonas200ResponseFromJSONTyped(json, false)
}

export function GetPersonas200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPersonas200Response {
  if (json == null) {
    return json
  }
  return {
    personas: (json['personas'] as Array<any>).map(PersonaFromJSON),
    cursor: json['cursor'] == null ? undefined : json['cursor'],
  }
}

export function GetPersonas200ResponseToJSON(
  json: any,
): GetPersonas200Response {
  return GetPersonas200ResponseToJSONTyped(json, false)
}

export function GetPersonas200ResponseToJSONTyped(
  value?: GetPersonas200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    personas: (value['personas'] as Array<any>).map(PersonaToJSON),
    cursor: value['cursor'],
  }
}
