/* tslint:disable */
/* eslint-disable */
/**
 * Numeno Article Recommender API
 * ### Introduction  Use the Numeno Article Recommender API to get personalized article recommendations in three easy steps:  1. Define a Persona: Simply provide a description of your interests, vibe, and target audience.  2. Associate the Persona with a Feed.  3. Pull from the Feed to receive a curated selection of articles from across the web.  ### Cross-Origin Resource Sharing This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/), allowing cross-domain communication from the browser. All responses have a wildcard same-origin policy which makes them accessible from any code on any site.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@numeno.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Information needed to update or create a persona.
 * @export
 * @interface PersonaUpdate
 */
export interface PersonaUpdate {
  /**
   * The name of the Persona for easy reference
   * @type {string}
   * @memberof PersonaUpdate
   */
  name?: string
  /**
   * The natural-language body of the Persona
   * @type {string}
   * @memberof PersonaUpdate
   */
  body?: string
}

/**
 * Check if a given object implements the PersonaUpdate interface.
 */
export function instanceOfPersonaUpdate(value: object): value is PersonaUpdate {
  return true
}

export function PersonaUpdateFromJSON(json: any): PersonaUpdate {
  return PersonaUpdateFromJSONTyped(json, false)
}

export function PersonaUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PersonaUpdate {
  if (json == null) {
    return json
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    body: json['body'] == null ? undefined : json['body'],
  }
}

export function PersonaUpdateToJSON(json: any): PersonaUpdate {
  return PersonaUpdateToJSONTyped(json, false)
}

export function PersonaUpdateToJSONTyped(
  value?: PersonaUpdate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    name: value['name'],
    body: value['body'],
  }
}
